// DefaultPromptDefinitions.ts
import type { PromptProfile } from '@model/Profile/PromptProfile';

export type PromptDefinition = Omit<PromptProfile, 'systemPrompt'>;

export const DEFAULT_PROMPT_DEFINITIONS: PromptDefinition[] = [
  { id: 'task-plan', purpose: 'Create a compact executable plan for the whole task before execution starts.', instructions: ['Plan the whole task, not merely the next operation.', 'Use only the supplied project index; do not request tools and do not invent files or APIs.', 'Use the smallest useful number of steps. Every step must have one concrete, verifiable goal.', 'For code changes, separate understanding from change preparation and file editing.', 'Use prepare-change to decide exactly what must change and edit-file to perform the concrete file edit.', 'End every plan with finalize. Add verify only when deterministic verification is useful.', 'Respect the supplied maximum attempt limits; never increase them.', 'Keep step goals concise and use the same natural language as the task where practical.'] },
  { id: 'recover-plan', purpose: 'Recover a stalled or exhausted plan step without restarting the whole task.', instructions: ['Diagnose only the current blocker using the supplied plan and recent execution evidence.', 'Prefer the smallest correction that can unblock the existing plan.', 'Use currentStepResult.missing as the authoritative blocker list. Insert steps only to resolve those concrete missing items.', 'You may retry the current step, insert up to three focused steps before it, skip it only when it is genuinely unnecessary, request human help, or fail clearly.', 'Use only the supplied available step types for inserted steps.', 'Do not edit files or solve the whole task inside recovery.', 'When a human hint is supplied, treat it as additional evidence and use it to guide the correction.', 'Do not silently discard completed plan steps.', 'Do not insert a step whose goal duplicates an already completed step or a previous recovery insertion. If no new evidence can be named, request human help instead of expanding the plan.'] },
  { id: 'plan', purpose: 'Choose only the next useful operation for the task.', instructions: ['Do not modify or read files in this operation.', 'Use the project file index, task, policies, knowledge, and short history only.', 'Do not request tools. Classify the task intent as read or write, then select the next intellectual operation using nextOperation.', 'For project-analysis tasks, normally choose understand.', 'For implementation tasks, choose understand first when project evidence is still needed; otherwise choose implement.', 'Keep message and observations very short.'] },
  { id: 'search', purpose: 'Locate evidence required by the current plan step.', instructions: ['Work only on the ACTIVE plan-step goal. Ignore future plan goals even when the full task mentions them.', 'Use search and filesystem tools instead of guessing paths.', 'After tool results arrive, explicitly decide whether the active goal is satisfied using stepResult.', 'Set stepResult.goalSatisfied=true as soon as the requested files/symbols/locations are found; do not spend remaining attempts searching for unrelated future information.', 'Record concise findings and evidence with file paths. Put only concrete unresolved items in stepResult.missing.'] },
  { id: 'understand', purpose: 'Build a focused understanding required by the current plan step.', instructions: ['Work only on the ACTIVE plan-step goal and use completedStepEvidence before requesting more files.', 'Read only the most important files needed for the current question.', 'Request at most 3 tool calls in one batch.', 'Separate facts visible in code from inferred intent.', 'Write concise factual observations after every evidence round so they can survive after raw file contents are dropped.', 'Do not broaden the active goal merely to gather more files.', 'After each evidence round, summarize what is known in stepResult.', 'If the supplied evidence is sufficient for the active goal, set stepResult.goalSatisfied=true instead of requesting more files.'] },
  { id: 'finalize', purpose: 'Produce the final answer using evidence already gathered.', instructions: ['Do not request tools and do not ask for more project evidence.', 'Use the task plus factual observations and execution history already supplied.', 'Return status=completed and put the complete user-facing response in finalAnswer.', 'The finalAnswer must be entirely in the requested response language. Do not answer in English when the response language is ru; English is allowed only for source-code identifiers, file paths, API names, and other technical identifiers.', 'Do not mention internal operation names, token budgets, or runtime mechanics unless the user asked about them.'] },
  { id: 'implement', purpose: 'Implement the requested project change.', instructions: ['Follow all supplied policies before generating code.', 'Prefer minimal changes and existing project patterns.', 'Use changes for file writes/deletes; use tools to inspect before editing.', 'Request verify only when useful; verification is not mandatory for every task.'] },
  { id: 'prepare-change', purpose: 'Prepare the exact file-level change before editing.', instructions: ['Work only on the ACTIVE plan-step goal.', 'Use completedStepEvidence to identify the minimum files and edits required.', 'Do not emit file changes and do not search broadly in this operation.', 'Return stepResult.goalSatisfied=true only when the target files and exact intended modifications are concrete.', 'If evidence is missing, return goalSatisfied=false and list the exact missing facts in stepResult.missing; let Recovery decide how to gather them.'] },
  { id: 'edit-file', purpose: 'Perform the concrete file edit described by the prepared change plan.', instructions: ['Focus only on the files and edits established by the plan and observations.', 'Inspect a target file only if its current content is not already available.', 'Emit changes as soon as enough evidence is available; do not re-plan the whole task.', 'Prefer minimal changes and preserve unrelated content.', 'After changes are produced, stop editing; PlanExecutor owns the next step.'] },
  { id: 'review', purpose: 'Review the current result or changes.', instructions: ['Check only the ACTIVE review goal, relevant policies, scope, and consistency with existing patterns.', 'Return stepResult with concrete findings/evidence and explicit missing blockers.', 'Do not rewrite code merely for stylistic preference unless policy requires it.'] },
  { id: 'verify', purpose: 'Verify the completed work when verification is useful.', instructions: ['Work only on the ACTIVE verification goal.', 'Choose focused checks rather than running everything by default.', 'Use terminal/git/filesystem tools as needed.', 'Return stepResult with the verification outcome and concrete evidence.'] },
  { id: 'resolve-failure', purpose: 'Resolve a concrete failure.', instructions: ['Use the failure evidence from execution history.', 'Decide whether to inspect more, implement a fix, ask the human, or fail clearly.', 'Avoid repeating an unchanged failed action.'] },
  { id: 'extract-knowledge', purpose: 'Extract reusable project knowledge candidates.', instructions: ['Do not present assumptions about WHY as confirmed decisions.', 'Prefer concrete patterns and understandings supported by project evidence.', 'This operation does not automatically persist knowledge in v0.1.'] },
];
