// DefaultPromptDefinitions.ts
import type { PromptProfile } from '@model/Profile/PromptProfile';

export type PromptDefinition = Omit<PromptProfile, 'systemPrompt'>;

export const DEFAULT_PROMPT_DEFINITIONS: PromptDefinition[] = [
  { id: 'task-plan', purpose: 'Create a compact executable plan for the whole task before execution starts.', instructions: ['Plan the whole task, not merely the next operation.', 'Use only the supplied project index; do not request tools and do not invent files or APIs.', 'Use the smallest useful number of steps. Every step must have one concrete, verifiable goal.', 'For code changes, separate understanding from change preparation and file editing.', 'Use prepare-change to decide exactly what must change and edit-file to perform the concrete file edit.', 'End every plan with finalize. Add verify only when deterministic verification is useful.', 'Respect the supplied maximum attempt limits; never increase them.', 'Keep step goals concise and use the same natural language as the task where practical.'] },
  { id: 'recover-plan', purpose: 'Recover a stalled or exhausted plan step without restarting the whole task.', instructions: ['Diagnose only the current blocker using the supplied plan and recent execution evidence.', 'Prefer the smallest correction that can unblock the existing plan.', 'You may retry the current step, insert up to three focused steps before it, skip it only when it is genuinely unnecessary, request human help, or fail clearly.', 'Use only the supplied available step types for inserted steps.', 'Do not edit files or solve the whole task inside recovery.', 'When a human hint is supplied, treat it as additional evidence and use it to guide the correction.', 'Do not silently discard completed plan steps.'] },
  { id: 'plan', purpose: 'Choose only the next useful operation for the task.', instructions: ['Do not modify or read files in this operation.', 'Use the project file index, task, policies, knowledge, and short history only.', 'Do not request tools. Classify the task intent as read or write, then select the next intellectual operation using nextOperation.', 'For project-analysis tasks, normally choose understand.', 'For implementation tasks, choose understand first when project evidence is still needed; otherwise choose implement.', 'Keep message and observations very short.'] },
  { id: 'search', purpose: 'Locate relevant evidence in the project.', instructions: ['Use search and filesystem tools instead of guessing paths.', 'Find the closest existing examples when the task asks for analogous implementation.', 'After enough evidence is found, move to understand or another justified operation.'] },
  { id: 'understand', purpose: 'Build a focused understanding of the relevant project area.', instructions: ['Read only the most important files needed for the current question.', 'Request at most 3 tool calls in one batch.', 'Separate facts visible in code from inferred intent.', 'Write concise factual observations after every evidence round so they can survive after raw file contents are dropped.', 'Do not return to plan merely to gather more files.', 'After at most two evidence rounds, use nextOperation=finalize for read-only tasks and nextOperation=implement for tasks that require project changes.', 'If the supplied evidence is already sufficient, transition to finalize instead of requesting more files.'] },
  { id: 'finalize', purpose: 'Produce the final answer using evidence already gathered.', instructions: ['Do not request tools and do not ask for more project evidence.', 'Use the task plus factual observations and execution history already supplied.', 'Return status=completed and put the complete user-facing response in finalAnswer.', 'The finalAnswer must be entirely in the requested response language. Do not answer in English when the response language is ru; English is allowed only for source-code identifiers, file paths, API names, and other technical identifiers.', 'Do not mention internal operation names, token budgets, or runtime mechanics unless the user asked about them.'] },
  { id: 'implement', purpose: 'Implement the requested project change.', instructions: ['Follow all supplied policies before generating code.', 'Prefer minimal changes and existing project patterns.', 'Use changes for file writes/deletes; use tools to inspect before editing.', 'Request verify only when useful; verification is not mandatory for every task.'] },
  { id: 'prepare-change', purpose: 'Prepare the exact file-level change before editing.', instructions: ['Use gathered evidence to identify the minimum files and edits required.', 'Do not emit file changes in this operation.', 'Return concise observations describing each target file and the exact intended modification.', 'If critical evidence is missing, request only the specific files needed; otherwise transition to edit-file.'] },
  { id: 'edit-file', purpose: 'Perform the concrete file edit described by the prepared change plan.', instructions: ['Focus only on the files and edits established by the plan and observations.', 'Inspect a target file only if its current content is not already available.', 'Emit changes as soon as enough evidence is available; do not re-plan the whole task.', 'Prefer minimal changes and preserve unrelated content.', 'After changes are produced, transition to review; do not start another implementation cycle unless review finds a concrete problem.'] },
  { id: 'review', purpose: 'Review the current result or changes.', instructions: ['Check the task, relevant policies, scope, and consistency with existing patterns.', 'Do not rewrite code merely for stylistic preference unless policy requires it.'] },
  { id: 'verify', purpose: 'Verify the completed work when verification is useful.', instructions: ['Choose focused checks rather than running everything by default.', 'Use terminal/git/filesystem tools as needed.', 'On failure, move to resolve-failure with concrete evidence.'] },
  { id: 'resolve-failure', purpose: 'Resolve a concrete failure.', instructions: ['Use the failure evidence from execution history.', 'Decide whether to inspect more, implement a fix, ask the human, or fail clearly.', 'Avoid repeating an unchanged failed action.'] },
  { id: 'extract-knowledge', purpose: 'Extract reusable project knowledge candidates.', instructions: ['Do not present assumptions about WHY as confirmed decisions.', 'Prefer concrete patterns and understandings supported by project evidence.', 'This operation does not automatically persist knowledge in v0.1.'] },
];
