// DefaultOperationProfile.ts
import type { OperationProfile } from '@operation/Profile/OperationProfile';

export const DEFAULT_OPERATION_PROFILES: OperationProfile[] = [
  {
    id: 'plan',
    costWeight: 1,
    allowedTransitions: ['search', 'understand', 'implement', 'finalize'],
    description: 'Choose the next useful intellectual operation for the task without reading or changing files.',
    promptId: 'plan',
    contextStrategy: 'planning',
    policyScopes: ['architecture', 'project'],
    fallback: 'understand',
    enabled: true,
  },
  {
    id: 'search',
    costWeight: 1,
    allowedTransitions: ['search', 'understand', 'implement', 'finalize'],
    description: 'Locate relevant project files, symbols, examples, and references.',
    promptId: 'search',
    contextStrategy: 'search',
    policyScopes: ['project'],
    fallback: 'understand',
    enabled: true,
  },
  {
    id: 'understand',
    costWeight: 2,
    allowedTransitions: ['understand', 'implement', 'review', 'finalize'],
    description: 'Understand existing code, responsibilities, dependencies, and project behavior.',
    promptId: 'understand',
    contextStrategy: 'understanding',
    policyScopes: ['architecture', 'project'],
    enabled: true,
  },
  {
    id: 'finalize',
    costWeight: 2,
    allowedTransitions: [],
    description: 'Produce the final user-facing answer from evidence and observations already gathered.',
    promptId: 'finalize',
    contextStrategy: 'finalization',
    policyScopes: ['architecture', 'project', 'review'],
    enabled: true,
  },
  {
    id: 'implement',
    costWeight: 4,
    allowedTransitions: ['implement', 'review', 'verify', 'finalize', 'resolve-failure'],
    description: 'Implement the requested change using existing project patterns and policies.',
    promptId: 'implement',
    contextStrategy: 'implementation',
    policyScopes: ['code', 'typescript', 'vue', 'api', 'form', 'entity'],
    fallback: 'understand',
    enabled: true,
  },
  {
    id: 'review',
    costWeight: 2,
    allowedTransitions: ['implement', 'verify', 'finalize', 'resolve-failure'],
    description: 'Review current changes for correctness, scope, consistency, and policy compliance.',
    promptId: 'review',
    contextStrategy: 'review',
    policyScopes: ['review', 'architecture', 'code'],
    fallback: 'understand',
    enabled: true,
  },
  {
    id: 'verify',
    costWeight: 2,
    allowedTransitions: ['finalize', 'implement', 'resolve-failure'],
    description: 'Optionally verify the result using appropriate deterministic checks and focused review.',
    promptId: 'verify',
    contextStrategy: 'verification',
    policyScopes: ['testing', 'review', 'code'],
    fallback: 'resolve-failure',
    enabled: true,
  },
  {
    id: 'resolve-failure',
    costWeight: 2,
    allowedTransitions: ['understand', 'implement', 'verify', 'finalize'],
    description: 'Analyze a failed operation or check and decide how to fix, replan, ask, or stop.',
    promptId: 'resolve-failure',
    contextStrategy: 'failure-analysis',
    policyScopes: ['code', 'testing', 'architecture'],
    fallback: 'understand',
    enabled: true,
  },
  {
    id: 'extract-knowledge',
    costWeight: 2,
    allowedTransitions: ['finalize'],
    description: 'Extract a reusable project understanding, pattern, decision candidate, or policy candidate.',
    promptId: 'extract-knowledge',
    contextStrategy: 'knowledge-extraction',
    policyScopes: ['project', 'architecture'],
    enabled: true,
  },
];
